<?php
/**
 * CreateDeliverabilityTestOptions
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MailSlurp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MailSlurp\Models;

use \ArrayAccess;
use \MailSlurp\ObjectSerializer;

/**
 * CreateDeliverabilityTestOptions Class Doc Comment
 *
 * @category Class
 * @description Create a new deliverability/load test
 * @package  MailSlurp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateDeliverabilityTestOptions implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateDeliverabilityTestOptions';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'description' => 'string',
        'scope' => 'string',
        'start_at' => '\DateTime',
        'max_duration_seconds' => 'int',
        'success_threshold_percent' => 'float',
        'selector' => '\MailSlurp\Models\DeliverabilitySelectorOptions',
        'expectations' => '\MailSlurp\Models\DeliverabilityExpectation[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'description' => null,
        'scope' => null,
        'start_at' => 'date-time',
        'max_duration_seconds' => 'int64',
        'success_threshold_percent' => 'double',
        'selector' => null,
        'expectations' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => true,
		'description' => true,
		'scope' => false,
		'start_at' => true,
		'max_duration_seconds' => true,
		'success_threshold_percent' => true,
		'selector' => false,
		'expectations' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'description' => 'description',
        'scope' => 'scope',
        'start_at' => 'startAt',
        'max_duration_seconds' => 'maxDurationSeconds',
        'success_threshold_percent' => 'successThresholdPercent',
        'selector' => 'selector',
        'expectations' => 'expectations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'description' => 'setDescription',
        'scope' => 'setScope',
        'start_at' => 'setStartAt',
        'max_duration_seconds' => 'setMaxDurationSeconds',
        'success_threshold_percent' => 'setSuccessThresholdPercent',
        'selector' => 'setSelector',
        'expectations' => 'setExpectations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'description' => 'getDescription',
        'scope' => 'getScope',
        'start_at' => 'getStartAt',
        'max_duration_seconds' => 'getMaxDurationSeconds',
        'success_threshold_percent' => 'getSuccessThresholdPercent',
        'selector' => 'getSelector',
        'expectations' => 'getExpectations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SCOPE_INBOX = 'INBOX';
    public const SCOPE_PHONE = 'PHONE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getScopeAllowableValues()
    {
        return [
            self::SCOPE_INBOX,
            self::SCOPE_PHONE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('scope', $data ?? [], null);
        $this->setIfExists('start_at', $data ?? [], null);
        $this->setIfExists('max_duration_seconds', $data ?? [], null);
        $this->setIfExists('success_threshold_percent', $data ?? [], null);
        $this->setIfExists('selector', $data ?? [], null);
        $this->setIfExists('expectations', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['scope'] === null) {
            $invalidProperties[] = "'scope' can't be null";
        }
        $allowedValues = $this->getScopeAllowableValues();
        if (!is_null($this->container['scope']) && !in_array($this->container['scope'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'scope', must be one of '%s'",
                $this->container['scope'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['max_duration_seconds']) && ($this->container['max_duration_seconds'] < 1)) {
            $invalidProperties[] = "invalid value for 'max_duration_seconds', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['success_threshold_percent']) && ($this->container['success_threshold_percent'] > 100.0)) {
            $invalidProperties[] = "invalid value for 'success_threshold_percent', must be smaller than or equal to 100.0.";
        }

        if (!is_null($this->container['success_threshold_percent']) && ($this->container['success_threshold_percent'] <= 0.0)) {
            $invalidProperties[] = "invalid value for 'success_threshold_percent', must be bigger than 0.0.";
        }

        if ($this->container['selector'] === null) {
            $invalidProperties[] = "'selector' can't be null";
        }
        if ($this->container['expectations'] === null) {
            $invalidProperties[] = "'expectations' can't be null";
        }
        if ((count($this->container['expectations']) > 20)) {
            $invalidProperties[] = "invalid value for 'expectations', number of items must be less than or equal to 20.";
        }

        if ((count($this->container['expectations']) < 1)) {
            $invalidProperties[] = "invalid value for 'expectations', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Optional name for the test
     *
     * @return self
     */
    public function setName($name)
    {

        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Optional description
     *
     * @return self
     */
    public function setDescription($description)
    {

        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return string
     */
    public function getScope()
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param string $scope Entity scope to evaluate
     *
     * @return self
     */
    public function setScope($scope)
    {
        $allowedValues = $this->getScopeAllowableValues();
        if (!in_array($scope, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'scope', must be one of '%s'",
                    $scope,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($scope)) {
            throw new \InvalidArgumentException('non-nullable scope cannot be null');
        }

        $this->container['scope'] = $scope;

        return $this;
    }

    /**
     * Gets start_at
     *
     * @return \DateTime|null
     */
    public function getStartAt()
    {
        return $this->container['start_at'];
    }

    /**
     * Sets start_at
     *
     * @param \DateTime|null $start_at UTC instant when the receive window starts. Defaults to now if omitted.
     *
     * @return self
     */
    public function setStartAt($start_at)
    {

        if (is_null($start_at)) {
            array_push($this->openAPINullablesSetToNull, 'start_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('start_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['start_at'] = $start_at;

        return $this;
    }

    /**
     * Gets max_duration_seconds
     *
     * @return int|null
     */
    public function getMaxDurationSeconds()
    {
        return $this->container['max_duration_seconds'];
    }

    /**
     * Sets max_duration_seconds
     *
     * @param int|null $max_duration_seconds Optional timeout in seconds after startAt. If not all entities match before timeout the test transitions to FAILED.
     *
     * @return self
     */
    public function setMaxDurationSeconds($max_duration_seconds)
    {

        if (!is_null($max_duration_seconds) && ($max_duration_seconds < 1)) {
            throw new \InvalidArgumentException('invalid value for $max_duration_seconds when calling CreateDeliverabilityTestOptions., must be bigger than or equal to 1.');
        }


        if (is_null($max_duration_seconds)) {
            array_push($this->openAPINullablesSetToNull, 'max_duration_seconds');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_duration_seconds', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['max_duration_seconds'] = $max_duration_seconds;

        return $this;
    }

    /**
     * Gets success_threshold_percent
     *
     * @return float|null
     */
    public function getSuccessThresholdPercent()
    {
        return $this->container['success_threshold_percent'];
    }

    /**
     * Sets success_threshold_percent
     *
     * @param float|null $success_threshold_percent Optional acceptable success threshold percentage (0,100]. If set, a timed-out test can complete successfully when matchedEntities/totalEntities reaches this percentage.
     *
     * @return self
     */
    public function setSuccessThresholdPercent($success_threshold_percent)
    {

        if (!is_null($success_threshold_percent) && ($success_threshold_percent > 100.0)) {
            throw new \InvalidArgumentException('invalid value for $success_threshold_percent when calling CreateDeliverabilityTestOptions., must be smaller than or equal to 100.0.');
        }
        if (!is_null($success_threshold_percent) && ($success_threshold_percent <= 0.0)) {
            throw new \InvalidArgumentException('invalid value for $success_threshold_percent when calling CreateDeliverabilityTestOptions., must be bigger than 0.0.');
        }


        if (is_null($success_threshold_percent)) {
            array_push($this->openAPINullablesSetToNull, 'success_threshold_percent');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('success_threshold_percent', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['success_threshold_percent'] = $success_threshold_percent;

        return $this;
    }

    /**
     * Gets selector
     *
     * @return \MailSlurp\Models\DeliverabilitySelectorOptions
     */
    public function getSelector()
    {
        return $this->container['selector'];
    }

    /**
     * Sets selector
     *
     * @param \MailSlurp\Models\DeliverabilitySelectorOptions $selector selector
     *
     * @return self
     */
    public function setSelector($selector)
    {

        if (is_null($selector)) {
            throw new \InvalidArgumentException('non-nullable selector cannot be null');
        }

        $this->container['selector'] = $selector;

        return $this;
    }

    /**
     * Gets expectations
     *
     * @return \MailSlurp\Models\DeliverabilityExpectation[]
     */
    public function getExpectations()
    {
        return $this->container['expectations'];
    }

    /**
     * Sets expectations
     *
     * @param \MailSlurp\Models\DeliverabilityExpectation[] $expectations One or more expectations to evaluate for each entity
     *
     * @return self
     */
    public function setExpectations($expectations)
    {

        if ((count($expectations) > 20)) {
            throw new \InvalidArgumentException('invalid value for $expectations when calling CreateDeliverabilityTestOptions., number of items must be less than or equal to 20.');
        }
        if ((count($expectations) < 1)) {
            throw new \InvalidArgumentException('invalid length for $expectations when calling CreateDeliverabilityTestOptions., number of items must be greater than or equal to 1.');
        }

        if (is_null($expectations)) {
            throw new \InvalidArgumentException('non-nullable expectations cannot be null');
        }

        $this->container['expectations'] = $expectations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


