<?php
/**
 * DeliverabilityAnalyticsRunDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MailSlurp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MailSlurp\Models;

use \ArrayAccess;
use \MailSlurp\ObjectSerializer;

/**
 * DeliverabilityAnalyticsRunDto Class Doc Comment
 *
 * @category Class
 * @description Run-level metrics for analytics tables
 * @package  MailSlurp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DeliverabilityAnalyticsRunDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DeliverabilityAnalyticsRunDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'scope' => 'string',
        'status' => 'string',
        'created_at' => '\DateTime',
        'start_at' => '\DateTime',
        'completed_at' => '\DateTime',
        'total_entities' => 'int',
        'matched_entities' => 'int',
        'unmatched_entities' => 'int',
        'completion_percentage' => 'float',
        'success_threshold_percent' => 'float',
        'threshold_status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'name' => null,
        'scope' => null,
        'status' => null,
        'created_at' => 'date-time',
        'start_at' => 'date-time',
        'completed_at' => 'date-time',
        'total_entities' => 'int64',
        'matched_entities' => 'int64',
        'unmatched_entities' => 'int64',
        'completion_percentage' => 'double',
        'success_threshold_percent' => 'double',
        'threshold_status' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'name' => true,
		'scope' => false,
		'status' => false,
		'created_at' => false,
		'start_at' => false,
		'completed_at' => true,
		'total_entities' => false,
		'matched_entities' => false,
		'unmatched_entities' => false,
		'completion_percentage' => false,
		'success_threshold_percent' => true,
		'threshold_status' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'scope' => 'scope',
        'status' => 'status',
        'created_at' => 'createdAt',
        'start_at' => 'startAt',
        'completed_at' => 'completedAt',
        'total_entities' => 'totalEntities',
        'matched_entities' => 'matchedEntities',
        'unmatched_entities' => 'unmatchedEntities',
        'completion_percentage' => 'completionPercentage',
        'success_threshold_percent' => 'successThresholdPercent',
        'threshold_status' => 'thresholdStatus'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'scope' => 'setScope',
        'status' => 'setStatus',
        'created_at' => 'setCreatedAt',
        'start_at' => 'setStartAt',
        'completed_at' => 'setCompletedAt',
        'total_entities' => 'setTotalEntities',
        'matched_entities' => 'setMatchedEntities',
        'unmatched_entities' => 'setUnmatchedEntities',
        'completion_percentage' => 'setCompletionPercentage',
        'success_threshold_percent' => 'setSuccessThresholdPercent',
        'threshold_status' => 'setThresholdStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'scope' => 'getScope',
        'status' => 'getStatus',
        'created_at' => 'getCreatedAt',
        'start_at' => 'getStartAt',
        'completed_at' => 'getCompletedAt',
        'total_entities' => 'getTotalEntities',
        'matched_entities' => 'getMatchedEntities',
        'unmatched_entities' => 'getUnmatchedEntities',
        'completion_percentage' => 'getCompletionPercentage',
        'success_threshold_percent' => 'getSuccessThresholdPercent',
        'threshold_status' => 'getThresholdStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SCOPE_INBOX = 'INBOX';
    public const SCOPE_PHONE = 'PHONE';
    public const STATUS_CREATED = 'CREATED';
    public const STATUS_SCHEDULED = 'SCHEDULED';
    public const STATUS_RUNNING = 'RUNNING';
    public const STATUS_PAUSED = 'PAUSED';
    public const STATUS_STOPPED = 'STOPPED';
    public const STATUS_COMPLETE = 'COMPLETE';
    public const STATUS_FAILED = 'FAILED';
    public const THRESHOLD_STATUS_NOT_CONFIGURED = 'NOT_CONFIGURED';
    public const THRESHOLD_STATUS_PASSING = 'PASSING';
    public const THRESHOLD_STATUS_FAILING = 'FAILING';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getScopeAllowableValues()
    {
        return [
            self::SCOPE_INBOX,
            self::SCOPE_PHONE,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_CREATED,
            self::STATUS_SCHEDULED,
            self::STATUS_RUNNING,
            self::STATUS_PAUSED,
            self::STATUS_STOPPED,
            self::STATUS_COMPLETE,
            self::STATUS_FAILED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getThresholdStatusAllowableValues()
    {
        return [
            self::THRESHOLD_STATUS_NOT_CONFIGURED,
            self::THRESHOLD_STATUS_PASSING,
            self::THRESHOLD_STATUS_FAILING,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('scope', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('start_at', $data ?? [], null);
        $this->setIfExists('completed_at', $data ?? [], null);
        $this->setIfExists('total_entities', $data ?? [], null);
        $this->setIfExists('matched_entities', $data ?? [], null);
        $this->setIfExists('unmatched_entities', $data ?? [], null);
        $this->setIfExists('completion_percentage', $data ?? [], null);
        $this->setIfExists('success_threshold_percent', $data ?? [], null);
        $this->setIfExists('threshold_status', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['scope'] === null) {
            $invalidProperties[] = "'scope' can't be null";
        }
        $allowedValues = $this->getScopeAllowableValues();
        if (!is_null($this->container['scope']) && !in_array($this->container['scope'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'scope', must be one of '%s'",
                $this->container['scope'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['start_at'] === null) {
            $invalidProperties[] = "'start_at' can't be null";
        }
        if ($this->container['total_entities'] === null) {
            $invalidProperties[] = "'total_entities' can't be null";
        }
        if ($this->container['matched_entities'] === null) {
            $invalidProperties[] = "'matched_entities' can't be null";
        }
        if ($this->container['unmatched_entities'] === null) {
            $invalidProperties[] = "'unmatched_entities' can't be null";
        }
        if ($this->container['completion_percentage'] === null) {
            $invalidProperties[] = "'completion_percentage' can't be null";
        }
        if ($this->container['threshold_status'] === null) {
            $invalidProperties[] = "'threshold_status' can't be null";
        }
        $allowedValues = $this->getThresholdStatusAllowableValues();
        if (!is_null($this->container['threshold_status']) && !in_array($this->container['threshold_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'threshold_status', must be one of '%s'",
                $this->container['threshold_status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {

        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }

        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {

        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return string
     */
    public function getScope()
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param string $scope scope
     *
     * @return self
     */
    public function setScope($scope)
    {
        $allowedValues = $this->getScopeAllowableValues();
        if (!in_array($scope, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'scope', must be one of '%s'",
                    $scope,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($scope)) {
            throw new \InvalidArgumentException('non-nullable scope cannot be null');
        }

        $this->container['scope'] = $scope;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }

        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {

        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }

        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets start_at
     *
     * @return \DateTime
     */
    public function getStartAt()
    {
        return $this->container['start_at'];
    }

    /**
     * Sets start_at
     *
     * @param \DateTime $start_at start_at
     *
     * @return self
     */
    public function setStartAt($start_at)
    {

        if (is_null($start_at)) {
            throw new \InvalidArgumentException('non-nullable start_at cannot be null');
        }

        $this->container['start_at'] = $start_at;

        return $this;
    }

    /**
     * Gets completed_at
     *
     * @return \DateTime|null
     */
    public function getCompletedAt()
    {
        return $this->container['completed_at'];
    }

    /**
     * Sets completed_at
     *
     * @param \DateTime|null $completed_at completed_at
     *
     * @return self
     */
    public function setCompletedAt($completed_at)
    {

        if (is_null($completed_at)) {
            array_push($this->openAPINullablesSetToNull, 'completed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('completed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['completed_at'] = $completed_at;

        return $this;
    }

    /**
     * Gets total_entities
     *
     * @return int
     */
    public function getTotalEntities()
    {
        return $this->container['total_entities'];
    }

    /**
     * Sets total_entities
     *
     * @param int $total_entities total_entities
     *
     * @return self
     */
    public function setTotalEntities($total_entities)
    {

        if (is_null($total_entities)) {
            throw new \InvalidArgumentException('non-nullable total_entities cannot be null');
        }

        $this->container['total_entities'] = $total_entities;

        return $this;
    }

    /**
     * Gets matched_entities
     *
     * @return int
     */
    public function getMatchedEntities()
    {
        return $this->container['matched_entities'];
    }

    /**
     * Sets matched_entities
     *
     * @param int $matched_entities matched_entities
     *
     * @return self
     */
    public function setMatchedEntities($matched_entities)
    {

        if (is_null($matched_entities)) {
            throw new \InvalidArgumentException('non-nullable matched_entities cannot be null');
        }

        $this->container['matched_entities'] = $matched_entities;

        return $this;
    }

    /**
     * Gets unmatched_entities
     *
     * @return int
     */
    public function getUnmatchedEntities()
    {
        return $this->container['unmatched_entities'];
    }

    /**
     * Sets unmatched_entities
     *
     * @param int $unmatched_entities unmatched_entities
     *
     * @return self
     */
    public function setUnmatchedEntities($unmatched_entities)
    {

        if (is_null($unmatched_entities)) {
            throw new \InvalidArgumentException('non-nullable unmatched_entities cannot be null');
        }

        $this->container['unmatched_entities'] = $unmatched_entities;

        return $this;
    }

    /**
     * Gets completion_percentage
     *
     * @return float
     */
    public function getCompletionPercentage()
    {
        return $this->container['completion_percentage'];
    }

    /**
     * Sets completion_percentage
     *
     * @param float $completion_percentage completion_percentage
     *
     * @return self
     */
    public function setCompletionPercentage($completion_percentage)
    {

        if (is_null($completion_percentage)) {
            throw new \InvalidArgumentException('non-nullable completion_percentage cannot be null');
        }

        $this->container['completion_percentage'] = $completion_percentage;

        return $this;
    }

    /**
     * Gets success_threshold_percent
     *
     * @return float|null
     */
    public function getSuccessThresholdPercent()
    {
        return $this->container['success_threshold_percent'];
    }

    /**
     * Sets success_threshold_percent
     *
     * @param float|null $success_threshold_percent success_threshold_percent
     *
     * @return self
     */
    public function setSuccessThresholdPercent($success_threshold_percent)
    {

        if (is_null($success_threshold_percent)) {
            array_push($this->openAPINullablesSetToNull, 'success_threshold_percent');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('success_threshold_percent', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['success_threshold_percent'] = $success_threshold_percent;

        return $this;
    }

    /**
     * Gets threshold_status
     *
     * @return string
     */
    public function getThresholdStatus()
    {
        return $this->container['threshold_status'];
    }

    /**
     * Sets threshold_status
     *
     * @param string $threshold_status threshold_status
     *
     * @return self
     */
    public function setThresholdStatus($threshold_status)
    {
        $allowedValues = $this->getThresholdStatusAllowableValues();
        if (!in_array($threshold_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'threshold_status', must be one of '%s'",
                    $threshold_status,
                    implode("', '", $allowedValues)
                )
            );
        }

        if (is_null($threshold_status)) {
            throw new \InvalidArgumentException('non-nullable threshold_status cannot be null');
        }

        $this->container['threshold_status'] = $threshold_status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


