<?php
/**
 * PhoneSummaryDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  MailSlurp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace MailSlurp\Models;

use \ArrayAccess;
use \MailSlurp\ObjectSerializer;

/**
 * PhoneSummaryDto Class Doc Comment
 *
 * @category Class
 * @package  MailSlurp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PhoneSummaryDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PhoneSummaryDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'phone_country_summaries' => '\MailSlurp\Models\PhoneSummaryCountryDto[]',
        'has_phone_numbers' => 'bool',
        'has_missing_plans' => 'bool',
        'total_phones' => 'int',
        'plans' => '\MailSlurp\Models\PlanSummaryDto[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'phone_country_summaries' => null,
        'has_phone_numbers' => null,
        'has_missing_plans' => null,
        'total_phones' => 'int32',
        'plans' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'phone_country_summaries' => false,
		'has_phone_numbers' => false,
		'has_missing_plans' => false,
		'total_phones' => false,
		'plans' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'phone_country_summaries' => 'phoneCountrySummaries',
        'has_phone_numbers' => 'hasPhoneNumbers',
        'has_missing_plans' => 'hasMissingPlans',
        'total_phones' => 'totalPhones',
        'plans' => 'plans'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'phone_country_summaries' => 'setPhoneCountrySummaries',
        'has_phone_numbers' => 'setHasPhoneNumbers',
        'has_missing_plans' => 'setHasMissingPlans',
        'total_phones' => 'setTotalPhones',
        'plans' => 'setPlans'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'phone_country_summaries' => 'getPhoneCountrySummaries',
        'has_phone_numbers' => 'getHasPhoneNumbers',
        'has_missing_plans' => 'getHasMissingPlans',
        'total_phones' => 'getTotalPhones',
        'plans' => 'getPlans'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('phone_country_summaries', $data ?? [], null);
        $this->setIfExists('has_phone_numbers', $data ?? [], null);
        $this->setIfExists('has_missing_plans', $data ?? [], null);
        $this->setIfExists('total_phones', $data ?? [], null);
        $this->setIfExists('plans', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['phone_country_summaries'] === null) {
            $invalidProperties[] = "'phone_country_summaries' can't be null";
        }
        if ($this->container['has_phone_numbers'] === null) {
            $invalidProperties[] = "'has_phone_numbers' can't be null";
        }
        if ($this->container['has_missing_plans'] === null) {
            $invalidProperties[] = "'has_missing_plans' can't be null";
        }
        if ($this->container['total_phones'] === null) {
            $invalidProperties[] = "'total_phones' can't be null";
        }
        if ($this->container['plans'] === null) {
            $invalidProperties[] = "'plans' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets phone_country_summaries
     *
     * @return \MailSlurp\Models\PhoneSummaryCountryDto[]
     */
    public function getPhoneCountrySummaries()
    {
        return $this->container['phone_country_summaries'];
    }

    /**
     * Sets phone_country_summaries
     *
     * @param \MailSlurp\Models\PhoneSummaryCountryDto[] $phone_country_summaries phone_country_summaries
     *
     * @return self
     */
    public function setPhoneCountrySummaries($phone_country_summaries)
    {

        if (is_null($phone_country_summaries)) {
            throw new \InvalidArgumentException('non-nullable phone_country_summaries cannot be null');
        }

        $this->container['phone_country_summaries'] = $phone_country_summaries;

        return $this;
    }

    /**
     * Gets has_phone_numbers
     *
     * @return bool
     */
    public function getHasPhoneNumbers()
    {
        return $this->container['has_phone_numbers'];
    }

    /**
     * Sets has_phone_numbers
     *
     * @param bool $has_phone_numbers has_phone_numbers
     *
     * @return self
     */
    public function setHasPhoneNumbers($has_phone_numbers)
    {

        if (is_null($has_phone_numbers)) {
            throw new \InvalidArgumentException('non-nullable has_phone_numbers cannot be null');
        }

        $this->container['has_phone_numbers'] = $has_phone_numbers;

        return $this;
    }

    /**
     * Gets has_missing_plans
     *
     * @return bool
     */
    public function getHasMissingPlans()
    {
        return $this->container['has_missing_plans'];
    }

    /**
     * Sets has_missing_plans
     *
     * @param bool $has_missing_plans has_missing_plans
     *
     * @return self
     */
    public function setHasMissingPlans($has_missing_plans)
    {

        if (is_null($has_missing_plans)) {
            throw new \InvalidArgumentException('non-nullable has_missing_plans cannot be null');
        }

        $this->container['has_missing_plans'] = $has_missing_plans;

        return $this;
    }

    /**
     * Gets total_phones
     *
     * @return int
     */
    public function getTotalPhones()
    {
        return $this->container['total_phones'];
    }

    /**
     * Sets total_phones
     *
     * @param int $total_phones total_phones
     *
     * @return self
     */
    public function setTotalPhones($total_phones)
    {

        if (is_null($total_phones)) {
            throw new \InvalidArgumentException('non-nullable total_phones cannot be null');
        }

        $this->container['total_phones'] = $total_phones;

        return $this;
    }

    /**
     * Gets plans
     *
     * @return \MailSlurp\Models\PlanSummaryDto[]
     */
    public function getPlans()
    {
        return $this->container['plans'];
    }

    /**
     * Sets plans
     *
     * @param \MailSlurp\Models\PlanSummaryDto[] $plans plans
     *
     * @return self
     */
    public function setPlans($plans)
    {

        if (is_null($plans)) {
            throw new \InvalidArgumentException('non-nullable plans cannot be null');
        }

        $this->container['plans'] = $plans;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


