<?php
/**
 * InlineObject1Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailSlurp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MailSlurp;

use PHPUnit\Framework\TestCase;

/**
 * InlineObject1Test Class Doc Comment
 *
 * @category    Class
 * @description Byte array request body
 * @package     MailSlurp
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InlineObject1Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InlineObject1"
     */
    public function testInlineObject1()
    {
    }

    /**
     * Test attribute "short"
     */
    public function testPropertyShort()
    {
    }

    /**
     * Test attribute "char"
     */
    public function testPropertyChar()
    {
    }

    /**
     * Test attribute "int"
     */
    public function testPropertyInt()
    {
    }

    /**
     * Test attribute "long"
     */
    public function testPropertyLong()
    {
    }

    /**
     * Test attribute "float"
     */
    public function testPropertyFloat()
    {
    }

    /**
     * Test attribute "double"
     */
    public function testPropertyDouble()
    {
    }

    /**
     * Test attribute "direct"
     */
    public function testPropertyDirect()
    {
    }

    /**
     * Test attribute "read_only"
     */
    public function testPropertyReadOnly()
    {
    }
}
