<?php
/**
 * SentEmailDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MailSlurp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MailSlurp API
 *
 * MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 *
 * The version of the OpenAPI document: 6.5.2
 * Contact: contact@mailslurp.dev
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MailSlurp;

use PHPUnit\Framework\TestCase;

/**
 * SentEmailDtoTest Class Doc Comment
 *
 * @category    Class
 * @description Sent email details
 * @package     MailSlurp
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SentEmailDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SentEmailDto"
     */
    public function testSentEmailDto()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "inbox_id"
     */
    public function testPropertyInboxId()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
    }

    /**
     * Test attribute "reply_to"
     */
    public function testPropertyReplyTo()
    {
    }

    /**
     * Test attribute "cc"
     */
    public function testPropertyCc()
    {
    }

    /**
     * Test attribute "bcc"
     */
    public function testPropertyBcc()
    {
    }

    /**
     * Test attribute "attachments"
     */
    public function testPropertyAttachments()
    {
    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {
    }

    /**
     * Test attribute "body_md5_hash"
     */
    public function testPropertyBodyMd5Hash()
    {
    }

    /**
     * Test attribute "body"
     */
    public function testPropertyBody()
    {
    }

    /**
     * Test attribute "charset"
     */
    public function testPropertyCharset()
    {
    }

    /**
     * Test attribute "is_html"
     */
    public function testPropertyIsHtml()
    {
    }

    /**
     * Test attribute "sent_at"
     */
    public function testPropertySentAt()
    {
    }

    /**
     * Test attribute "pixel_ids"
     */
    public function testPropertyPixelIds()
    {
    }

    /**
     * Test attribute "message_id"
     */
    public function testPropertyMessageId()
    {
    }
}
